// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // Sử dụng DIRECT_URL cho migrations (không qua pooler)
    // Fallback về DATABASE_URL nếu không có DIRECT_URL
    url: process.env.DIRECT_URL || process.env.DATABASE_URL,
  },
});
